### ISSUE TITLE
Label mapping

### ISSUE THREAD

**Issue by LuketheDukeBates** [mye1225/multilingual_content_mod#1]
Hello! I enjoyed your paper and this looks like a really cool dataset! I am wondering if you could provide an official mapping between the integer label and a string that designates its meaning. For example, 0 -- 'neutral', 1 -- 'toxic', 2 -- 'rule violation', etc.

Thanks so much!

**Comment by mye1225** [comment]
Thanks for your interest in our work. Label 0 and 1 stands for "non-removed" and "removed" comment, respectively.

**Comment by LuketheDukeBates** [comment]
Awesome, thanks!
